baseURL = 'https://tridentmoon.netlify.app'
languageCode = 'en-us'
title = 'Trident Moon'

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'



[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'page'




googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/trident_favicon.jpg"
  site_logo = ""
  headdescription = "Promoting and teaching Ashtanga Yoga in Central Kentucky.  Ashtanga, pranayama, Sanskrit, meditation, Georgetown Kentucky."
  #facebook = "https://www.facebook.com/profile.php?id=61556987980351"
  #instagram = "https://www.instagram.com/tridentmoonyoga"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/shiva_moon_landscape-2.jpg"
  recent_posts_number = 2
  cover_dimming_class = "bg-black-00"
  site_header_text_background_color = "rgba(50, 50, 50, 0.7);"
  page_header_text_background_color = "rgba(50, 50, 50, 0.7)"
  custom_css = ["css/custom.css"]

[params.ananke]
  show_recent_posts = false # do not show recent posts on home page

[params.ananke.social.follow]
  new_window_icon = false
  networks = [
    "facebook",
    "instagram"
  ]

[params.ananke.social.instagram]
username = "tridentmoonyoga"

[params.ananke.social.facebook]
profilelink = "https://www.facebook.com/profile.php?id=61556987980351"

[params.ananke.social.email]
profilelink = "mailto:tridentmoonyoga@gmail.com"


[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "ashtanga"
  name = "Aṣṭāṅga"
  url = "/ashtanga/"
  weight = 2

[[menu.main]]
  identifier = "teacher"
  name = "Teacher"
  url = "/teacher/"
  weight = 3 


[[menu.main]]
  identifier = "classes"
  name = "Classes"
  url = "/classes/"
  weight = 4 

[[menu.main]]
  identifier = "post"
  name = "Blog"
  url = "/post/"
  weight = 6 

[[menu.main]]
  identifier = "articles"
  name = "Resources"
  url = "/articles/"
  weight = 5 





